// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  author_page: dynamic(() => import("./AuthorPage")),
  book_page: dynamic(() => import("./BookPage")),
  call_to_action: dynamic(() => import("./CallToAction")),
  hero: dynamic(() => import("./Hero")),
  library: dynamic(() => import("./Library")),
};
